In [10]:
def variance(data):
     
     n = len(data)
     
     mean = sum(data) / n
     
     deviations = [(x - mean) ** 2 for x in data]
     
     variance = sum(deviations) / n
     return variance

In [11]:
variance([4, 8, 6, 5, 3, 2, 8, 9, 2, 5])

5.76

In [12]:
import math

In [13]:
def variance(data, ddof=0):
     n = len(data)
     mean = sum(data) / n
     return sum((x - mean) ** 2 for x in data) / (n - ddof)


In [14]:
def stdev(data):
     var = variance(data)
     std_dev = math.sqrt(var)
     return std_dev

In [15]:
stdev([3,4,6,7,8,5,6,7])

1.5612494995995996

In [16]:
a = [2,4,10,6,8,4]
 amin, amax = min(a), max(a)
 for i, val in enumerate(a):
    a[i] = (val-amin) / (amax-amin)

IndentationError: unexpected indent (<ipython-input-16-71076890070d>, line 2)

In [102]:
a = [2,4,10,6,8,4]

In [103]:
 xmin, xmax = min(a), max(a)

In [105]:
print("value : normalized value\n")
for x in a:
    n= (x-xmin) / (xmax-xmin)
print("{} : {}".format(x,n))
          

value : normalized value

4 : 0.25


In [101]:
print("{} : {}" .format(x,n))

4 : 0.25


In [21]:
def my_mean(sample):
...     return sum(sample) / len(sample)

In [22]:
def my_median(sample):
...     n = len(sample)
...     index = n // 2
...    
...     if n % 2:
...         return sorted(sample)[index]
...     
...     return sum(sorted(sample)[index - 1:index + 1]) / 2
...

In [23]:
def variance(data, ddof=0):
     n = len(data)
     mean = sum(data) / n
     return sum((x - mean) ** 2 for x in data) / (n - ddof)


In [86]:
b = [2,4,10,6,8,4]

In [106]:
a = [2,4,10,6,8,4]
xmin = min(a)
xmax = max(a)
print("value : normalized value\n")
for x in a:
    n = (x-xmin)/(xmax - xmin)
    print("{} : {}".format(x,n))

value : normalized value

2 : 0.0
4 : 0.25
10 : 1.0
6 : 0.5
8 : 0.75
4 : 0.25


In [110]:
import math
a = [2,4,10,6,8,4]
mean=sum(a)/len(a)
variance = sum((i - mean) ** 2 for i in a) / len(a)
sd=variance**0.5
print("value : stand value\n")
for x in a:
    s = (x-mean)/sd 
    print("{} : {}".format(x,s))


value : stand value

2 : -1.3643820804812932
4 : -0.6201736729460424
10 : 1.6124515496597098
6 : 0.12403473458920836
8 : 0.8682431421244592
4 : -0.6201736729460424


In [1]:
import numpy as np
dataset = np.array([1.0, 12.4, 3.9, 10.4])
normalized_dataset = (dataset - np.min(dataset)) / (np.max(dataset) - np.min(dataset))
print(normalized_dataset)

[0.         1.         0.25438596 0.8245614 ]


In [2]:
def dataset_minmax(dataset1):
    minmax = list()
    for i in range(len(dataset1[0])):
        col_values = [row[i] for row in dataset1]
        value_min = min(col_values)
        value_max = max(col_values)
        minmax.append([value_min, value_max])
    return minmax
 

def normalize_dataset(dataset1,minmax):
    for row in dataset1:
        for i in range(len(row)):
            row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 

dataset1= [[50, 30], [20, 90]]
print(dataset1)

minmax = dataset_minmax(dataset1)
print(minmax)

normalize_dataset(dataset1,minmax)
print(dataset1)

[[50, 30], [20, 90]]
[[20, 50], [30, 90]]
[[1.0, 0.0], [0.0, 1.0]]


In [3]:
from sklearn.preprocessing import Normalizer
X = [[4, 1, 2, 2],
     [1, 3, 9, 3],
     [5, 7, 5, 1]]
transformer = Normalizer().fit(X)  # fit does nothing.
transformer
transformer.transform(X)

array([[0.8, 0.2, 0.4, 0.4],
       [0.1, 0.3, 0.9, 0.3],
       [0.5, 0.7, 0.5, 0.1]])

In [4]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
print("Scaler used: ",scaler.fit(data))

print("Scaler mean:",scaler.mean_)

print("Tranform data:",scaler.transform(data))
print("Data",scaler.transform([[2, 2]]))
import numpy as np
dataset = np.array([1.0, 12.4, 3.9, 10.4])
normalized_dataset = (dataset - np.min(dataset)) / (np.max(dataset) - np.min(dataset))
print(normalized_dataset)

Scaler used:  StandardScaler()
Scaler mean: [0.5 0.5]
Tranform data: [[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
Data [[3. 3.]]
[0.         1.         0.25438596 0.8245614 ]


In [9]:
 #k-means clustering

import math
cluster1 = []
cluster2 = []
cluster3 = []
x1,y1 = 6.2,3.2
x2,y2 = 6.6,3.7
x3,y3 = 6.5,3.0
points =[[5.9,3.2],
         [4.6,2.9],
         [6.2,2.8],
         [4.7,3.2],
         [5.5,4.2],
         [5.0,3.0],
         [4.9,3.1],
         [6.7,3.1],
         [5.1,3.8],
         [6.0,3.0]]

def eucledian_distance(a,b):
    dis1 = math.sqrt((a-x1)**2 + (b-y1)**2)
    dis2 = math.sqrt((a-x2)**2 + (b-y2)**2)
    dis3 = math.sqrt((a-x3)**2 + (b-y3)**2)
    mind = min(dis1,dis2,dis3)
    if(mind == dis1):
        cluster1.append([a,b])
    elif(mind == dis2):
        cluster2.append([a,b])
    else:
        cluster3.append([a,b])
        
for i,j in points:
    eucledian_distance(i,j)

print(cluster1)
print(cluster2)
print(cluster3)
sumi = 0
sumj = 0
for i,j in cluster1:
    sumi = sumi + i
    sumj = sumj + j
nx1 = round(sumi/len(cluster1),2)
ny1 = round(sumj/len(cluster1),2)
print(nx1,ny1)

[[5.9, 3.2], [4.6, 2.9], [4.7, 3.2], [5.0, 3.0], [4.9, 3.1], [5.1, 3.8], [6.0, 3.0]]
[[5.5, 4.2]]
[[6.2, 2.8], [6.7, 3.1]]
5.17 3.17


In [36]:
import numpy as np
import pandas as pd
from copy import deepcopy

In [37]:
def euclidean(a,b, ax=1):
    return np.linalg.norm(a-b, axis=ax)

In [38]:
k = 3
X = pd.read_csv('data.csv',index_col=False)
print(X)

     x    y
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.7  3.8
9  6.0  3.0


In [39]:
X = pd.read_csv('data.csv',index_col=False)
x1 = X['x'].values
x2 = X['y'].values
X = np.array(list(zip(x1, x2)))
print(X)

[[5.9 3.2]
 [4.6 2.9]
 [6.2 2.8]
 [4.7 3.2]
 [5.5 4.2]
 [5.  3. ]
 [4.9 3.1]
 [6.7 3.1]
 [5.7 3.8]
 [6.  3. ]]


In [40]:
C_x = [6.2, 6.6 ,6.5]
C_y = [3.2, 3.7, 3.0]
Centroid = np.array(list(zip(C_x, C_y)), dtype=np.float32)
print("Initial Centroids")
print(Centroid.shape)

Initial Centroids
(3, 2)


In [41]:
Centroid_old = np.zeros(Centroid.shape)
print(Centroid_old)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [42]:
clusters = np.zeros(len(X))
print(clusters)
error = euclidean(Centroid, Centroid_old, None)
print(error)
iterr = 0

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
12.537144692236463


In [43]:

while error != 0:

    iterr = iterr + 1
    for i in range(len(X)):
       
        distances = euclidean(X[i], Centroid)
        
        cluster = np.argmin(distances)
        clusters[i] = cluster

    Centroid_old = deepcopy(Centroid)
        
    
    for p in range(k):
        points = [X[j] for j in range(len(X)) if clusters[j] == p]
        Centroid[p] = np.mean(points, axis=0)
    print(" Centre of the clusters after ", iterr," Iteration \n", Centroid)
    error = euclidean(Centroid, Centroid_old, None)
    print("Error  ... ",error)  


 Centre of the clusters after  1  Iteration 
 [[5.257143  3.1714287]
 [5.5       4.2      ]
 [6.45      2.95     ]]
Error  ...  1.5345341
 Centre of the clusters after  2  Iteration 
 [[4.8   3.05 ]
 [5.6   4.   ]
 [6.2   3.025]]
Error  ...  0.5846789
 Centre of the clusters after  3  Iteration 
 [[4.8   3.05 ]
 [5.6   4.   ]
 [6.2   3.025]]
Error  ...  0.0


In [29]:
import pandas as pd
import numpy as np


In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mtp  


In [46]:
data = pd.read_csv('data.csv')

In [47]:
data

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0      aardvark     1         0     0     1         0        0         1   
1      antelope     1         0     0     1         0        0         0   
2          bass     0         0     1     0         0        1         1   
3          bear     1         0     0     1         0        0         1   
4          boar     1         0     0     1         0        0         1   
..          ...   ...       ...   ...   ...       ...      ...       ...   
96      wallaby     1         0     0     1         0        0         0   
97         wasp     1         0     1     0         1        0         0   
98         wolf     1         0     0     1         0        0         1   
99         worm     0         0     1     0         0        0         0   
100        wren     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  class_type  
0          1           1  
1          1           1  
2          0           4  
3          1           1  
4          1           1  
..       ...         ...  
96         1           1  
97         0           6  
98         1           1  
99         0           7  
100        0           2  

[101 rows x 18 columns]

In [48]:
x1=data['hair'].values
x2=data['feathers'].values
x3=data['eggs'].values
x4=data['milk'].values
x5=data['airborne'].values
x6=data['aquatic'].values
x7=data['predator'].values
x8=data['toothed'].values
x9=data['backbone'].values
x10=data['breathes'].values
x11=data['venomous'].values
x12=data['fins'].values
x13=data['legs'].values
x14=data['tail'].values
x15=data['domestic'].values
x16=data['catsize'].values
y =data['class_type'].values



In [49]:
X = np.array(list(zip(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16)))

In [50]:
X

array([[1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0]])

In [51]:
Y=y
Y

array([1, 1, 4, 1, 1, 1, 1, 4, 4, 1, 1, 2, 4, 7, 7, 7, 2, 1, 4, 1, 2, 2,
       1, 2, 6, 5, 5, 1, 1, 1, 6, 1, 1, 2, 4, 1, 1, 2, 4, 6, 6, 2, 6, 2,
       1, 1, 7, 1, 1, 1, 1, 6, 5, 7, 1, 1, 2, 2, 2, 2, 4, 4, 3, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 7, 4, 1, 1, 3, 7, 2, 2, 3, 7, 4, 2, 1, 7, 4, 2,
       6, 5, 3, 3, 4, 1, 1, 2, 1, 6, 1, 7, 2])

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.25)


In [53]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
from sklearn import tree

In [54]:
decision = tree.DecisionTreeClassifier(criterion='gini')
decision.fit(X_train,y_train)

y_predict=decision.predict(X_test)
y_score = accuracy_score(y_test,y_predict)

In [55]:
print('Accuracy: ', y_score)
y_test

Accuracy:  0.8461538461538461


array([5, 2, 1, 1, 4, 7, 1, 7, 1, 7, 6, 4, 2, 5, 1, 4, 1, 5, 4, 7, 1, 6,
       3, 2, 2, 1])

In [56]:
print(classification_report(y_test,y_predict))



              precision    recall  f1-score   support

           1       1.00      1.00      1.00         8
           2       1.00      1.00      1.00         4
           3       0.50      1.00      0.67         1
           4       1.00      1.00      1.00         4
           5       1.00      0.67      0.80         3
           6       0.40      1.00      0.57         2
           7       1.00      0.25      0.40         4

    accuracy                           0.85        26
   macro avg       0.84      0.85      0.78        26
weighted avg       0.93      0.85      0.84        26



In [57]:
print(confusion_matrix(y_test,y_predict))

[[8 0 0 0 0 0 0]
 [0 4 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 1 0 2 0 0]
 [0 0 0 0 0 2 0]
 [0 0 0 0 0 3 1]]
